realm=${COTURN_REALM}
external-ip=${COTURN_EXTERNAL_IP}
use-auth-secret
static-auth-secret=${COTURN_STATIC_AUTH_SECRET}
tls-listening-port=${PORT_TURN_TLS:-3245}
min-port=${PORT_TURN_RELAY_MIN:-3261}
max-port=${PORT_TURN_RELAY_MAX:-3280}
log-file=/dev/stdout
no-stdout-log
fingerprint
no-multicast-peers
